# Generated by Django 5.2.13 on 2026-04-27 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
                'db_table': 'portfolio_user_profile',
            },
        ),
        migrations.CreateModel(
            name='PublicPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_slug', models.SlugField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('portfolio_website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='portfolio_profiles/')),
                ('skills', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfoliotemplate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_public_portfolio',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['username_slug'], name='portfolio_p_usernam_d46538_idx'), models.Index(fields=['is_published', 'is_featured'], name='portfolio_p_is_publ_b1e816_idx')],
            },
        ),
    ]
