# Generated by Django 5.2.13 on 2026-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_userprofile_publicportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='processed_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles_processed/'),
        ),
        migrations.AddField(
            model_name='publicportfolio',
            name='processed_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_profiles_processed/'),
        ),
        migrations.AlterField(
            model_name='portfoliotemplate',
            name='category',
            field=models.CharField(choices=[('minimalist', 'Minimalist'), ('developer', 'Developer-Focused'), ('creative', 'Creative/Designer'), ('corporate', 'Corporate/Professional'), ('latest', 'Latest')], max_length=20),
        ),
    ]
